In [2]:
# Daily Rainfall Prediction

import pandas as pd
import numpy as np
import warnings; warnings.simplefilter('ignore') # Jupyter notebook warning message remove

#importing the dataset
df = pd.read_csv('data/f2.2.csv') # dataset updated: f2.2.csv
# print(df)

#result of independentvariable
X = df.iloc[:,0:-3].values 
print(X)
# #result of dependent variable
y = df.iloc[:,-3].values
print(y)

# X=X.astype(int)
# y=y.astype(float)

[[2012    1    1 ...    4   19    5]
 [2012    1    2 ...    2   11    2]
 [2012    1    3 ...    4   14    6]
 ...
 [2018    6   22 ...    3   27   11]
 [2018    6   23 ...    2   26   11]
 [2018    6   24 ...    2   23   13]]
[ 0.    0.    0.   ...  7.87 21.08 21.08]


In [4]:
df.describe().T

count         mean        std     min      25%     50%  \
year             2366.0  2014.759510   1.881720  2012.0  2013.00  2015.0   
month            2366.0     6.295013   3.446608     1.0     3.00     6.0   
day              2366.0    15.687236   8.786559     1.0     8.00    16.0   
temp high        2366.0    30.175824   2.953112    14.0    28.00    31.0   
temp avg         2366.0    26.248521   3.417272    13.0    24.00    27.0   
temp low         2366.0    22.448014   4.303256     9.0    19.00    24.0   
DP high          2366.0    23.633559   4.076400    10.0    21.00    26.0   
DP avg           2366.0    21.841505   4.725065     7.0    18.00    24.0   
DP low           2366.0    19.612849   5.738022     0.0    15.00    22.0   
humidity high    2366.0    91.925190   5.837466    48.0    89.00    94.0   
humidity avg     2366.0    74.769653  10.567121    33.0    70.00    76.0   
humidity low     2366.0    54.501268  16.946496     4.0    42.00    57.0   
SLP high         2366.0  1009.966610   5.186352   994.0  1006.00  1010.0   
SLP avg          2366.0  1007.671175   4.902007   991.0  1004.00  1008.0   
SLP low          2366.0  1005.558749   4.972539   978.0  1002.00  1006.0   
visibility high  2366.0     5.292899   1.970396     2.0     4.25     5.0   
visibility avg   2366.0     4.438292   1.064215     1.0     4.00     5.0   
visibility low   2366.0     2.908707   1.506614     0.0     2.00     3.0   
wind high        2366.0    22.175824  14.815466     0.0    14.00    19.0   
wind avg         2366.0     8.486052   4.870980     0.0     5.00     8.0   
Rainfall         2366.0     3.330516  14.786862     0.0     0.00     0.0   
Unnamed: 22       365.0     9.980822  34.567614     0.0     0.00     0.0   

                     75%     max  
year             2016.00  2018.0  
month               9.00    12.0  
day                23.00    31.0  
temp high          32.00    51.0  
temp avg           29.00    39.0  
temp low           26.00    29.0  
DP high            27.00    32.0  
DP avg             26.00    28.0  
DP low             24.00    27.0  
humidity high      95.00   100.0  
humidity avg       82.00    99.0  
humidity low       66.00    94.0  
SLP high         1014.00  1061.0  
SLP avg          1012.00  1018.0  
SLP low          1010.00  1017.0  
visibility high     6.00    27.0  
visibility avg      5.00     7.0  
visibility low      4.00     6.0  
wind high          23.00   193.0  
wind avg           11.00    37.0  
Rainfall            0.51   463.0  
Unnamed: 22         3.00   463.0

Correlation 

In [5]:
df.corr()

year     month       day  temp high  temp avg  temp low  \
year             1.000000 -0.115276 -0.007211   0.149142  0.057563 -0.017810   
month           -0.115276  1.000000  0.011802   0.075993  0.182644  0.238627   
day             -0.007211  0.011802  1.000000  -0.018966 -0.010450 -0.003998   
temp high        0.149142  0.075993 -0.018966   1.000000  0.890852  0.725472   
temp avg         0.057563  0.182644 -0.010450   0.890852  1.000000  0.949690   
temp low        -0.017810  0.238627 -0.003998   0.725472  0.949690  1.000000   
DP high          0.040323  0.251681 -0.004275   0.692287  0.886314  0.913925   
DP avg           0.000895  0.289695 -0.000064   0.644142  0.869641  0.922976   
DP low          -0.013013  0.313142  0.010974   0.553364  0.792077  0.865428   
humidity high   -0.080782  0.260857  0.027531  -0.096098  0.061088  0.151918   
humidity avg    -0.127483  0.332325  0.010395   0.024089  0.355501  0.532287   
humidity low    -0.152749  0.256859  0.008854   0.069726  0.419478  0.605711   
SLP high         0.083533 -0.151145  0.010738  -0.429382 -0.643759 -0.720609   
SLP avg          0.074576 -0.148170 -0.000985  -0.462178 -0.676540 -0.749678   
SLP low          0.058381 -0.154815 -0.006644  -0.473597 -0.680079 -0.746846   
visibility high -0.073367  0.090066 -0.025137   0.291913  0.325774  0.310552   
visibility avg  -0.179604  0.188027 -0.022142   0.627327  0.699617  0.676723   
visibility low  -0.118712  0.158030  0.004901   0.499411  0.585623  0.589559   
wind high        0.102681 -0.097320 -0.002484   0.103311  0.121814  0.116100   
wind avg         0.075682 -0.181397  0.009125   0.127862  0.232487  0.277062   
Rainfall        -0.064762  0.047056 -0.000094  -0.052045  0.045055  0.109650   
Unnamed: 22           NaN  0.043019  0.001679  -0.000558  0.107874  0.152576   

                  DP high    DP avg    DP low  humidity high     ...       \
year             0.040323  0.000895 -0.013013      -0.080782     ...        
month            0.251681  0.289695  0.313142       0.260857     ...        
day             -0.004275 -0.000064  0.010974       0.027531     ...        
temp high        0.692287  0.644142  0.553364      -0.096098     ...        
temp avg         0.886314  0.869641  0.792077       0.061088     ...        
temp low         0.913925  0.922976  0.865428       0.151918     ...        
DP high          1.000000  0.965287  0.891300       0.340762     ...        
DP avg           0.965287  1.000000  0.952195       0.379458     ...        
DP low           0.891300  0.952195  1.000000       0.388837     ...        
humidity high    0.340762  0.379458  0.388837       1.000000     ...        
humidity avg     0.657166  0.733035  0.750236       0.683544     ...        
humidity low     0.656435  0.740109  0.803193       0.478421     ...        
SLP high        -0.707219 -0.730231 -0.692553      -0.216686     ...        
SLP avg         -0.738215 -0.759021 -0.716289      -0.227250     ...        
SLP low         -0.739853 -0.757184 -0.712323      -0.226764     ...        
visibility high  0.284531  0.287066  0.267522       0.005839     ...        
visibility avg   0.606544  0.606301  0.565127      -0.073606     ...        
visibility low   0.500031  0.509249  0.475578      -0.165394     ...        
wind high        0.102222  0.090716  0.072807      -0.074284     ...        
wind avg         0.208422  0.209936  0.188502      -0.165108     ...        
Rainfall         0.139383  0.142726  0.143041       0.173167     ...        
Unnamed: 22      0.172909  0.175688  0.152549       0.145959     ...        

                 SLP high   SLP avg   SLP low  visibility high  \
year             0.083533  0.074576  0.058381        -0.073367   
month           -0.151145 -0.148170 -0.154815         0.090066   
day              0.010738 -0.000985 -0.006644        -0.025137   
temp high       -0.429382 -0.462178 -0.473597         0.291913   
temp avg        -0.643759 -0.676540 -0.680079         0.325774   
temp low    

### KNN

In [6]:
# KNN

# X=X.astype(int)
# y=y.astype(int)

X = np.array(X)
y = np.array(y)

from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsRegressor

r_square_list = []

for i in range(1,100):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = i)

    neigh = KNeighborsRegressor(n_neighbors=8)
    neigh.fit(X_train,y_train)

    predicted = neigh.predict(X_test)
    #print("Prediction Result: ",predicted)
    #print("i = ",i)
    r_square = neigh.score(X_test,y_test)
    r_square_list.append(r_square)
    #print('R-squared test score: {:.3f}'.format(neigh.score(X_test_n,y_test_n))) # R-Squared test score

max_r_square = max(r_square_list)
print('Maximum R-squared test score: {:.3f}'.format(max_r_square)) # R-Squared test score

Maximum R-squared test score: 0.465


### Feature Scaling KNN

In [7]:
# Feature Scaling KNN

import warnings; warnings.simplefilter('ignore') # Jupyter notebook warning message remove
# Feature Scaling- MinMaxScaler
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()

r_square_list = []
for i in range(1,100):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = i)

    # Feature Scaling- MinMaxScaler

    X_train_n = scaler.fit_transform(X_train) # X_train_n = normalized
    X_test_n = scaler.fit_transform(X_test)
    y_train_n = scaler.fit_transform(y_train)
    y_test_n = scaler.fit_transform(y_test)

    neigh = KNeighborsRegressor(n_neighbors=8)
    neigh.fit(X_train_n,y_train_n)

    predicted = neigh.predict(X_test_n)
    #print("Prediction Result: ",predicted)
    #print("i = ",i)
    r_square = neigh.score(X_test_n,y_test_n)
    r_square_list.append(r_square)
    #print('R-squared test score: {:.3f}'.format(neigh.score(X_test_n,y_test_n))) # R-Squared test score

max_r_square = max(r_square_list)
print('Maximum R-squared test score: {:.3f}'.format(max_r_square)) # R-Squared test score

#Undo the scaling of X according to feature_range.    
X_train_d = scaler.inverse_transform(X_train_n) # X_train_d = dnormalized
X_test_d = scaler.inverse_transform(X_test_n)
y_train_d = scaler.inverse_transform(y_train_n)
y_test_d = scaler.inverse_transform(y_test_n)
predicted_d = scaler.inverse_transform(predicted)  

Maximum R-squared test score: 0.356


### Random Forest

In [4]:
# Random Forest
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt

#regressor = RandomForestRegressor(random_state=0, n_estimators=200, max_depth=None, max_features=1, min_samples_leaf=1, min_samples_split=2, bootstrap=False)
r_square_list = []
mae_list = []
rmse_list = []
mse_list = []

for i in range(1,100):
    #regressor = RandomForestRegressor(max_depth=None, random_state=i)
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = i)
    regressor = RandomForestRegressor(n_estimators=50, max_depth=None, max_features=1, min_samples_leaf=1, min_samples_split=2, bootstrap=False)
    regressor.fit(X_train, y_train)

    predicted = regressor.predict(X_test)
    #print("Prediction Result: ",predicted1)
    #print("i = ",i)

    #print('R-squared test score: {:.3f}'.format(regressor.score(X_test,y_test))) # R-Squared test score
    r_square = regressor.score(X_test,y_test)
    r_square_list.append(r_square)
    
    # calculate MAE
    mae = mean_absolute_error(y_test, predicted)
    mae_list.append(mae)
    
    # calculate MSE
    mse = mean_squared_error(y_test, predicted)
    mse_list.append(mse)
    
    # calculate RMSE
    rmse = sqrt(mean_squared_error(y_test, predicted))
    rmse_list.append(rmse)
    

max_r_square = max(r_square_list)
print('Maximum R-squared test score: {:.3f}'.format(max_r_square)) # R-Squared test score
min_mae = min(mae_list)
print('MAE: %.3f' % min_mae)

min_mse = min(mse_list)
print('MSE: %.3f' % min_mse)
min_rmse = min(rmse_list)
print('RMSE: %.3f' % min_rmse)

Maximum R-squared test score: 0.626
MAE: 2.692
MSE: 29.110
RMSE: 5.395


### Random Forest- Cross Validation

In [67]:
# Random Forest- Cross Validation
#https://www.kaggle.com/dansbecker/cross-validation
    
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Imputer
my_pipeline = make_pipeline(Imputer(), RandomForestRegressor())

from sklearn.model_selection import cross_val_score
scores1 = cross_val_score(my_pipeline, X, y, scoring='r2', cv=5)
print(scores1)
print('R^2 score: %2f' %(-1 * scores1.mean()))

scores2 = cross_val_score(my_pipeline, X, y, scoring='neg_mean_absolute_error')
print(scores2)
print('Mean Absolute Error %2f' %(-1 * scores2.mean()))

[ 2.20035578e-01  3.38956251e-04 -1.94947716e-01 -8.45612004e-01
  2.13461575e-01]
R^2 score: 0.121345
[-5.29856907 -3.80083143 -4.33233376]
Mean Absolute Error 4.477245


### Feature Scaling Random Forest

In [9]:
# Feature Scaling Random Forest

import warnings; warnings.simplefilter('ignore') # Jupyter notebook warning message remove

# Feature Scaling- MinMaxScaler
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()


from sklearn.ensemble import RandomForestRegressor

#regressor = RandomForestRegressor(random_state=0, n_estimators=200, max_depth=None, max_features=1, min_samples_leaf=1, min_samples_split=2, bootstrap=False)
r_square_list = []
for i in range(1,100):
    #regressor = RandomForestRegressor(max_depth=None, random_state=i)
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = i)

    # Feature Scaling- MinMaxScaler

    X_train_n = scaler.fit_transform(X_train)
    X_test_n = scaler.fit_transform(X_test)
    y_train_n = scaler.fit_transform(y_train)
    y_test_n = scaler.fit_transform(y_test)

    regressor = RandomForestRegressor(n_estimators=200, max_depth=None, max_features=1, min_samples_leaf=1, min_samples_split=2, bootstrap=False)
    regressor.fit(X_train_n, y_train_n)

    predicted = regressor.predict(X_test_n)
    #print("Prediction Result: ",predicted)
    #print("i = ",i)

    #print('R-squared test score: {:.3f}'.format(regressor.score(X_test_n,y_test_n))) # R-Squared test score
    r_square = regressor.score(X_test_n,y_test_n)
    r_square_list.append(r_square)

max_r_square = max(r_square_list)
print('Maximum R-squared test score: {:.3f}'.format(max_r_square)) # R-Squared test score

#Undo the scaling of X according to feature_range.    
X_train_d = scaler.inverse_transform(X_train_n)
X_test_d = scaler.inverse_transform(X_test_n)
y_train_d = scaler.inverse_transform(y_train_n)
y_test_d = scaler.inverse_transform(y_test_n)
predicted_d = scaler.inverse_transform(predicted)

Maximum R-squared test score: 0.432


### Neural Networks and Backpropogation
https://www.youtube.com/watch?v=X8SPO875mQY

In [5]:
from sklearn.cross_validation import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = 100)

# nn = MLPRegressor(
#     hidden_layer_sizes=(10,),  activation='relu', solver='adam', alpha=0.001, batch_size='auto',
#     learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=1000, shuffle=True,
#     random_state=9, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
#     early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

nn = MLPRegressor(hidden_layer_sizes=(10, ), activation='relu', solver='adam', alpha=0.0001, batch_size='auto', 
                  learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, 
                  random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, 
                  early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

nn.fit(X_train, y_train)
pred=nn.predict(X_test)

r_square = nn.score(X_test,y_test)
print('R-squared test score:',r_square)

# calculate MAE
mae = mean_absolute_error(y_test, pred)
print('Test MAE: %.3f' % mae)

# calculate MSE
mse = mean_squared_error(y_test, pred)
print('Test MSE: %.3f' % mse)

# calculate RMSE
rmse = sqrt(mean_squared_error(y_test, pred))
print('Test RMSE: %.3f' % rmse)

R-squared test score: 0.010204184360411594
Test MAE: 8.735
Test MSE: 1008.885
Test RMSE: 31.763


### NN- Cross Validation

In [70]:
# NN- Cross Validation
from sklearn.neural_network import MLPRegressor

# nn = MLPRegressor(
#     hidden_layer_sizes=(10,),  activation='relu', solver='adam', alpha=0.001, batch_size='auto',
#     learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=1000, shuffle=True,
#     random_state=9, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
#     early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

nn = MLPRegressor(hidden_layer_sizes=(10, ), activation='relu', solver='adam', alpha=0.0001, batch_size='auto', 
                  learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, 
                  random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, 
                  early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

nn.fit(X_train, y_train)
pred=nn.predict(X_test)

r_square = nn.score(X_test,y_test)
print(r_square)

0.057777862995772145


### LSTM

In [6]:
# https://machinelearningmastery.com/multivariate-time-series-forecasting-lstms-keras/
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

from sklearn.metrics import mean_absolute_error

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.10,random_state = 40)

# reshape input to be 3D [samples, timesteps, features]
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

# design network
model = Sequential()
model.add(LSTM(50, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(1))
model.compile(loss='mae', optimizer='adam')
# fit network
history = model.fit(X_train, y_train, epochs=50, batch_size=72, validation_data=(X_test, y_test), verbose=2, shuffle=False)
# plot history
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()

# make a prediction
yhat = model.predict(X_test)
X_test = X_test.reshape((X_test.shape[0], X_test.shape[2]))

# calculate MAE
mae = mean_absolute_error(y_test, yhat)
print('Test MAE: %.3f' % mae)

# calculate MSE
mse = mean_squared_error(y_test, yhat)
print('Test MSE: %.3f' % mse)

# calculate RMSE
rmse = sqrt(mean_squared_error(y_test, yhat))
print('Test RMSE: %.3f' % rmse)

Using TensorFlow backend.


(2129, 1, 20) (2129,) (237, 1, 20) (237,)
Train on 2129 samples, validate on 237 samples
Epoch 1/50
4s - loss: 3.4857 - val_loss: 2.0892
Epoch 2/50
0s - loss: 3.4694 - val_loss: 2.0864
Epoch 3/50
0s - loss: 3.4682 - val_loss: 2.0851
Epoch 4/50
0s - loss: 3.4683 - val_loss: 2.0874
Epoch 5/50
0s - loss: 3.4697 - val_loss: 2.0877
Epoch 6/50
0s - loss: 3.4703 - val_loss: 2.0875
Epoch 7/50
0s - loss: 3.4707 - val_loss: 2.0888
Epoch 8/50
0s - loss: 3.4706 - val_loss: 2.0871
Epoch 9/50
0s - loss: 3.4701 - val_loss: 2.0885
Epoch 10/50
0s - loss: 3.4706 - val_loss: 2.0871
Epoch 11/50
0s - loss: 3.4696 - val_loss: 2.0876
Epoch 12/50
0s - loss: 3.4703 - val_loss: 2.0894
Epoch 13/50
1s - loss: 3.4705 - val_loss: 2.0875
Epoch 14/50
0s - loss: 3.4699 - val_loss: 2.0880
Epoch 15/50
0s - loss: 3.4704 - val_loss: 2.0878
Epoch 16/50
0s - loss: 3.4698 - val_loss: 2.0881
Epoch 17/50
0s - loss: 3.4695 - val_loss: 2.0882
Epoch 18/50
0s - loss: 3.4694 - val_loss: 2.0886
Epoch 19/50
1s - loss: 3.4700 - val_lo

Test MAE: 2.088
Test MSE: 29.130
Test RMSE: 5.397
